In [119]:
# importing pandas, matplotlib and seaborn
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [120]:
#reading the csv file i.e our data 
data = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
data

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [121]:
#Getting information about our data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           374 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [122]:
# Number of rows and columns
data.shape

(374, 13)

In [123]:
# mapping categories of quality of sleep
sleep_quality_map = {1:'Poor',2:'Poor',3:'Poor',4:'Poor', 5:'Good',6:'Good',7:'Good',8:'Excellent',9:'Excellent', 10:'Excellent'}
data['sleep_quality'] = data['Quality of Sleep'].map(sleep_quality_map)
data

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,sleep_quality
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None,Good
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None,Good
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None,Good
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Poor
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Excellent
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Excellent
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Excellent
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Excellent
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Excellent

In [124]:
# People with poor qality of sleep i.e less than 5
data.loc[data['Quality of Sleep']<5]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,sleep_quality
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Poor
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Poor
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia,Poor
80,81,Female,34,Scientist,5.8,4,32,8,Overweight,131/86,81,5200,Sleep Apnea,Poor
81,82,Female,34,Scientist,5.8,4,32,8,Overweight,131/86,81,5200,Sleep Apnea,Poor

In [125]:
# Viewing Quality of Sleep vs sleep_quality column which we added
data.iloc[:, 5:14:8]

     Quality of Sleep sleep_quality
0                   6          Good
1                   6          Good
2                   6          Good
3                   4          Poor
4                   4          Poor
..                ...           ...
369                 9     Excellent
370                 9     Excellent
371                 9     Excellent
372                 9     Excellent
373                 9     Excellent

[374 rows x 2 columns]

In [126]:
#The columns present in our data
data.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps',
       'Sleep Disorder', 'sleep_quality'],
      dtype='object')

In [127]:
# function of BMI values
def BMI_values(BMI):
    if BMI == 'Underweight':
        return 'Below 18'
    elif BMI == 'Normal' or BMI == 'Normal Weight':
        return '18 to 25'
    elif BMI == 'Overweight':
        return '25 to 30'
    elif BMI == 'Obese':
        return 'Above 30'

In [128]:
#Applying our function
data['BMI_Values'] = data['BMI Category'].apply(BMI_values)
data.head(10)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,sleep_quality,BMI_Values
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None,Good,25 to 30
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None,Good,18 to 25
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None,Good,18 to 25
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Poor,Above 30
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Poor,Above 30
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia,Poor,Above 30
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia,Good,Above 30
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None,Good,18 to 25
8,9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None,Good,18 to 25
9,10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None,Good,18 to 25

In [129]:
# information of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           374 non-null    object
 13  sleep_quality            374 non-null    object
 14  BMI_Values               374 non-null    object
dtypes: float64(1), int64(7), object(7)
memory usage: 44.0+ KB

In [130]:
data.to_excel('sleepHealthLifestyle.xlsx', index=False)